### PR TITLE
Fix: list directory parsing errors/integration issues

### PR DESCRIPTION
**Pull request by jsonsivar**
## Description
List directory response was not returning fields properly.  This adds the required parsing and formatting of response so that it aligns with the what the FE expects.

Fixes # (issue)
https://app.clubhouse.io/terminalsystems/story/21125/listdirectory-missing-fields

## Type of change
Which of the commands should be ran for updating the API docs?

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [x] Unit Test
- [x] Integration Test

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by perfectmak — APPROVED** [review]
LGTM

**Review by maurycy — APPROVED** [review]
LGTM.

**Review by gpuente — APPROVED** [review]
@jsonsivar LGTM, just a qq: the `path` property is pointing to the ipfs path or the filepath inside the bucket?

**Comment by jsonsivar** [comment]
> @jsonsivar LGTM, just a qq: the `path` property is pointing to the ipfs path or the filepath inside the bucket?

This changes makes its so the `path` field is inside the bucket, not the ipfs path.

**Pull request merged**
